# --------------- General Settings ---------------

language: java

matrix:
  include:
    - dist: trusty
      jdk: oraclejdk8
    - dist: xenial
      jdk: openjdk11

# without this, the build errors after ~50 commits since the last release,
# because the latest tag is no longer available and the version cannot be determined
git:
  depth: false

# --------------- Gradle Cache ---------------

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
